CREATE DATABASE IF NOT EXISTS bemobi;

use bemobi;

CREATE TABLE IF NOT EXISTS `URLS` (
	`ID` int NOT NULL AUTO_INCREMENT,
    `ALIAS` varchar(255) NOT NULL,
    `URL` varchar(255) NOT NULL,
    `RETRIEVAL_COUNT` int DEFAULT 0,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `Alias` (`Alias`)
);
